<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>wait_for_firstrow</name>
   <tag></tag>
   <elementGuidId>70443d37-af6d-492b-b948-6f8a21dd14d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class=&quot;k-grid-content-locked&quot;]//tbody/tr[1]</value>
   </webElementProperties>
</WebElementEntity>
