<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>click_saveallocatequickit</name>
   <tag></tag>
   <elementGuidId>ee4aaa60-cb25-4d35-905c-c50dff6b0de9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[@class=&quot;right&quot;]//input[@id=&quot;SL_SO_SAVE&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//li[@class=&quot;right&quot;]//input[@id=&quot;SL_SO_SAVE&quot;]</value>
   </webElementProperties>
</WebElementEntity>
