<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>validate_statusfield</name>
   <tag></tag>
   <elementGuidId>c250a6af-9f33-4acb-85b9-fdc1eee033c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//label[@id=&quot;LBL_SL_SO_HEDR_STATUS&quot;]/../following-sibling::li/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//label[@id=&quot;LBL_SL_SO_HEDR_STATUS&quot;]/../following-sibling::li/label</value>
   </webElementProperties>
</WebElementEntity>
