<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>click_packfilter</name>
   <tag></tag>
   <elementGuidId>468a40db-5e66-4f28-8477-d17ed9b0d098</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//button[@type=&quot;submit&quot;])[${findex}]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//button[@type=&quot;submit&quot;])[${findex}]</value>
   </webElementProperties>
</WebElementEntity>
