<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>status_field</name>
   <tag></tag>
   <elementGuidId>4bbb2e91-c117-47da-adc2-7916be7f2710</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//label[@id=&quot;LBL_SM_MA_CUST_STATUS&quot;]/../following-sibling::li/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//label[@id=&quot;LBL_SM_MA_CUST_STATUS&quot;]/../following-sibling::li/label</value>
   </webElementProperties>
</WebElementEntity>
