<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>confirmation_popup_unitPrice</name>
   <tag></tag>
   <elementGuidId>4ff45e53-ce57-4e44-b6b4-9d11909b7670</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id=&quot;confirm_popup_window&quot;]//input[@value='No']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id=&quot;confirm_popup_window&quot;]//input[@value='No']</value>
   </webElementProperties>
</WebElementEntity>
