<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>OrderNumberFiltering_Generate</name>
   <tag></tag>
   <elementGuidId>0ee6f44d-326f-4d03-8453-2ef0d378b976</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;WH_SHIP_GRID&quot;]/div[2]/div[1]/table/thead/tr/th[6]/a[1]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;WH_SHIP_GRID&quot;]/div[2]/div[1]/table/thead/tr/th[6]/a[1]/span</value>
   </webElementProperties>
</WebElementEntity>
